name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
projects: ["stephan192/hochwasserportal"]
assignees: ["stephan192"]
body:
  - type: textarea
    id: related_problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: suggested_solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: ex. It would be helpfull when [...]
    validations:
      required: true
  - type: textarea
    id: alternatives_considered
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
